### ISSUE TITLE
Analysis notebook breaks when retrieving resolution

### ISSUE THREAD

**Issue by fatipardo** [fatipardo/PDBClean-0.0.2#105]
When running the Analysis notebook with eukaryotic ribosome dataset, the following error message appears:

`ValueError                                Traceback (most recent call last)
Input In [6], in <cell line: 3>()
      1 # Populate dataframe
      2 # Funcion prints items to screen
----> 3 df=make_pdb_df(trajdir, readdir, trajlist)

Input In [2], in make_pdb_df(trajdir, readdir, trajlist)
     74 for res in res_keys:
     75     if res in mmcif_dict and (mmcif_dict[res][0] != '?'):
---> 76           resolution.append(float(mmcif_dict[res][0]))
     77           break
     78 else:

ValueError: could not convert string to float: '.'`

The structure that is causing the problem is: 3jaj.cif

To fix, add new clause in if statement to account for '.'

**Comment by fatipardo** [comment]
The new code still breaks when processing the same structure: 3jaj

```---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [8], in <cell line: 3>()
      1 # Populate dataframe
      2 # Funcion prints items to screen
----> 3 df=make_pdb_df(trajdir, readdir, trajlist)

Input In [7], in make_pdb_df(trajdir, readdir, trajlist)
     74 for res in res_keys:
     75     if res in mmcif_dict and ((mmcif_dict[res][0] != '?') or (mmcif_dict[res][0] != '.')):
---> 76           resolution.append(float(mmcif_dict[res][0]))
     77           break
     78 else:

ValueError: could not convert string to float: '.' 

I can't figure out why it doesn't work

**Comment by fatipardo** [comment]
I recommend downloading structure PDB: 3JAJ 
in case you want to reproduce the error.

**Comment by fatipardo** [comment]
Ok, figures it out. We were using the wrong conditional, we should have used an "AND" instead of "OR", see how I fixed it below:

```
        for res in res_keys:
            if res in mmcif_dict and ((mmcif_dict[res][0] != '?') and (mmcif_dict[res][0] != '.')):
                  resolution.append(float(mmcif_dict[res][0]))
                  break
        else:
            resolution.append(0) 

```

@gdkwxn could you please check all the functions in the analysis notebook and fix them?

**Comment by gdkwxn** [comment]
Hi, yes I fixed the logical operators to be 'and'

**Comment by fatipardo** [comment]
Fixed! solved here: 
[https://github.com/fatipardo/PDBClean-0.0.2/pull/107#issue-2431125425](url)
