### ISSUE TITLE
Bug in src/pdbcleanchainstandardizationutils.py 

### ISSUE THREAD

**Issue by gdkwxn** [fatipardo/PDBClean-0.0.2#154]
When running the script for Step 3, the script crashes.

1) Select Standard Sequences from a chosen input structure -> 2) Select input structure -> 3) Remove chains from Standard Sequences -> crash

- It's a typo in the code, 
    - Standard_Sequences = remove_chains_from_standard(**Standard_Sequence**)
    - It should be "Standard_Sequence**s**"

**Comment by gdkwxn** [comment]
I believe this is a bug present for everyone who runs it, but if someone else would like to see if it crashes for them too, that would be great!

**Comment by gdkwxn** [comment]
take

**Comment by fatipardo** [comment]
> I believe this is a bug present for everyone who runs it, but if someone else would like to see if it crashes for them too, that would be great!
> 
> I also tested it with the fixed typo and it no longer crashed

Good catch @gdkwxn !

I hadn't tried those particular options before.
