### ISSUE TITLE
How to change name on yml file?

### ISSUE THREAD

**Issue by Liv-Weiner** [fatipardo/PDBClean-0.0.2#36]
I do not remember how to change the name of the yml file so that I can make a different environment with it. What do I have to type into my terminal?

**Comment by fatipardo** [comment]
The yml file is a text file, so you can open it using any text editor. We have been using vi. The name of the environment is the first line of the text file.

**Comment by Liv-Weiner** [comment]
The issue was that I was not in my notebooks directory inside of my PDBClean directory. Once in it, I typed "vi environment.yml".
